server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:community
    driver-class-name: org.h2.Driver
    username: sa
    password:

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  access-token-exp-seconds: 1800
  refresh-token-exp-seconds: 1209600